name: tankobon
description: tankobon client
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  dio: ^4.0.6
  connectivity_plus: ^2.3.5
  auto_route: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
  auto_route_generator: ^4.2.0
  mocktail: ^0.3.0
  widgetbook: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
